use gwiazdy

USE HoteleBaza;
GO

insert into Pañstwo values ('Hiszpania')
insert into Pañstwo values ('W³ochy')
insert into Pañstwo values ('Polska')
insert into Pañstwo values ('Niemcy')
insert into Pañstwo values ('Grecja')
insert into Pañstwo values ('Chorwacja')
insert into Pañstwo values ('Bu³garia')

insert into Miasto values ('Warszawa','3')
insert into Miasto values ('Zagrzeb','6')
insert into Miasto values ('Sofia','7')
insert into Miasto values ('Drezno','4')
insert into Miasto values ('Ateny','5')
insert into Miasto values ('Florencja','2')
insert into Miasto values ('Berlin','4')
insert into Miasto values ('Wenecja','2')
insert into Miasto values ('Rzym','2')
insert into Miasto values ('Kraków','3')
insert into Miasto values ('Madryt','1')

insert into Standard_Hotelu values ('1gwiazdkowy',1)
insert into Standard_Hotelu values ('2gwiazdkowy',1.5)
insert into Standard_Hotelu values ('3gwiazdkowy',2)
insert into Standard_Hotelu values ('4gwiazdkowy',2.5)
insert into Standard_Hotelu values ('5gwiazdkowy',3)

insert into Hotele values ('1','Hilton Hotel','5','9')
insert into Hotele values ('2','Palace Hotel','3','12')
insert into Hotele values ('3','Suite Hotel','4','2')
insert into Hotele values ('4','Ibis Hotel','4','10')
insert into Hotele values ('5','Marina athens','2','16')
insert into Hotele values ('6','Columbus','3','5')
insert into Hotele values ('7','Berlinare','5','0')
insert into Hotele values ('8','Belle Arti','3','2')
insert into Hotele values ('9','Rome Hotel','1','11')
insert into Hotele values ('10','Hotel na Wawelu','2','3')
insert into Hotele values ('1','Plaza','4','0')
insert into Hotele values ('6','Florentina','1','3')
insert into Hotele values ('7','H4','5','0')
insert into Hotele values ('11','Espania Hotel','1','11')

insert into Pokoje1 values ('1','350','1klasa')
insert into Pokoje1 values ('1','450','2klasa')
insert into Pokoje1 values ('2','700','1klasa')
insert into Pokoje1 values ('2','850','2klasa')
insert into Pokoje1 values ('3','900','1klasa')
insert into Pokoje1 values ('3','1050','2klasa')

insert into Wy¿ywienie values ('BB','80','wege')
insert into Wy¿ywienie values ('BB','100', 'miesna')
insert into Wy¿ywienie values ('FB','400','wege')
insert into Wy¿ywienie values ('FB','450','miesna')
insert into Wy¿ywienie values ('Al','600','wege')
insert into Wy¿ywienie values ('Al','750','miesna')

insert into Goœæ values ('Maria','Nowak', '123333453','maria.nowak@gmail.com')
insert into Goœæ values ('Marlena','¯uk', '789001259','marlena.zuk@gmail.com')
insert into Goœæ values ('Justyna','Kêpa', '569856859','justynak@gmail.com')
insert into Goœæ values ('Janusz','Polski', '999982372','januszz@gmail.com')
insert into Goœæ values ('Micha³','Cerazy', '898777654','michas@gmail.com')
insert into Goœæ values ('Konrad','Paras', '226677889','konri@gmail.com')
insert into Goœæ values ('Mateusz','Jasny', '886655446','mati.jasny@gmail.com')
insert into Goœæ values ('Magdalena','Pieczarka', '569118559','madziap@gmail.com')
insert into Goœæ values ('Jacek','Morski', '907998232','j.morski@gmail.com')
insert into Goœæ values ('Beata','Dobra', '999877654','dobra@gmail.com')

insert into Zamówienie values('1','2','3','4', '2018-01-01')
insert into Zamówienie values('2','2','2','2', '2018-01-02')
insert into Zamówienie values('3','3','3','3', '2018-01-03')
insert into Zamówienie values('4','4','1','1', '2018-01-04')
insert into Zamówienie values('10','6','5','2', '2018-01-05')
insert into Zamówienie values('7','7','6','3', '2018-01-06')
insert into Zamówienie values('5','3','3','6', '2018-01-07')
insert into Zamówienie values('6','5','4','5', '2018-01-08')
insert into Zamówienie values('8','1','3','6', '2018-01-09')
insert into Zamówienie values('9','10','4','5', '2018-01-10')
